const USERS = [
    { user: "admin", pass: "123456789", name: "Thầy Việt Anh Toán"},
    { user: "va", pass: "go", name: "Thầy Trần Việt Anh"},
    { user: "bon", pass: "123", name: "con Trần Nguyễn Hải Đăng", role: "vip"},
    { user: "0907291079", pass: "abc123", name: "Thầy Đoàn Văn Lãm" },
    { user: "loind", pass: "123", name: "Thầy Nguyễn Đức Lợi" },
    { user: "tctoan", pass: "21101994", name: "Thầy Thái Công Toãn" },
    { user: "ntt", pass: "ntt123", name: "Thầy Nguyễn Thái Thông" },
    { user: "xuxutit", pass: "1", name: "Thầy Đỗ Minh Tuân" },
    { user: "lamdang", pass: "123", name: "Cô Đặng Thị Lâm" },
    { user: "nvc", pass: "abc123", name: "Thầy Nguyễn Văn Cường" },
    { user: "vanminhthoai", pass: "2002", name: "Thầy Văn Minh Thoại" },
    { user: "dvk", pass: "123", name: "Thầy Dương Vĩ Khang" },
    { user: "at", pass: "123", name: "Thầy Bùi Trần Đức Anh Thái" },
    { user: "sondt", pass: "Latex@123456", name: "Thầy Đinh Thái Sơn" },
    { user: "ntd", pass: "123", name: "Thầy Nguyễn Tri Đức" },
    { user: "phc", pass: "123", name: "Cô Phùng Hoàng Cúc" },
    { user: "ttt", pass: "123", name: "Cô Tô Thị Thảo"},
    { user: "ntp", pass: "123", name: "Thầy Nguyễn Tuấn Phú" },
    { user: "dtt", pass: "123", name: "Thầy Đặng Thành Thắng" },
    { user: "qm11111111111", pass: "123aaaaaaaaaaaaaaaaaaaaaaa", name: "Thầy Lê Hồ Quang Minh" },
    { user: "dtb", pass: "123", name: "Thầy Đặng Thái Bình" },
    { user: "nda", pass: "123", name: "Thầy Nguyễn Đình Ảnh" },
    { user: "ha", pass: "123", name: "Thầy Hoàng Anh" },
    { user: "tbh", pass: "123", name: "Thầy Trần Bá Hưng" },
    { user: "tnc", pass: "123", name: "Thầy Trần Như Cang" },
    { user: "ptt", pass: "123", name: "Thầy Phan Tất Tín" },
    { user: "ntv", pass: "123", name: "Thầy Nguyễn Tiến Vũ" },
    { user: "lhl", pass: "123", name: "Thầy Lê Hoàng Lâm" },
    { user: "npt", pass: "123", name: "Thầy Nguyễn Phước Thịnh" },
    { user: "hvt", pass: "123", name: "Thầy Hà Văn Thận" },    
    { user: "tlva", pass: "123", name: "Cô Trần Lê Vân Anh" },
    { user: "lsv", pass: "123", name: "Thầy Lê Sơn Vương" }
];
